### ISSUE TITLE
Некорректно работающая кнопка назад в тулбаре

### ISSUE THREAD

**Issue by FrediKats** [bukhmastov/CDOITMO#4]
При нажатии на кнопку назад на тулбаре находясь в любой из категорий настроек, приложение переходит не обратно, в настройки, а возвращается на главный экран (в моем случае на электронный журнал). Это похоже на баг, немного не противоречит UX.

**Comment by bukhmastov** [comment]
Не баг, но уже и не фича. Так что согласен, текущая модель с одноуровневой вложенностью (https://developer.android.com/training/design-navigation/ancestral-temporal#sibling-screens) устарела после переработки настроек. Надо будет внедрять поддержку многоуровневой линейной вложенности окон. Видимо уже к следующему релизу.

**Comment by FrediKats** [comment]
Могу добавить интересный факт. Нажатие на кнопку назад работает нормально т.е. возвращает действительно в настройки, а не на главную.

**Comment by bukhmastov** [comment]
Кнопка вверх (в тулбаре) и назад теперь работают одинаково: 53ba65b
