### ISSUE TITLE
Скрытие занятий

### ISSUE THREAD

**Issue by FutureXpo** [bukhmastov/CDOITMO#5]
При скрытии одного занятия (английского по субботам) скрывается также и второе занятие этого предмета( в моем случае занятие во вторник). Если так изначально задумано, то почему нельзя после этого восстановить занятия по кнопке на занятии во вторник. Если так не задумано, то это баг?

**Comment by bukhmastov** [comment]
Это баг. Должно скрываться только одно занятие или несколько, если они полностью идентичны (с учетом дня и времени). Укажите, пожалуйста, номер группы (для расписания) и версию приложения.

**Comment by FutureXpo** [comment]
Version 1.16.1
B3200
