### ISSUE TITLE
Сообщение с пустыми аргументами в телеграме

### ISSUE THREAD

**Issue by FrediKats** [bukhmastov/CDOITMO#6]
Прилетело вот такое вот забавное сообщение в телеграм.
![image](https://user-images.githubusercontent.com/22368203/51422318-9c815000-1bbd-11e9-8b78-3d94ca366851.png)
M3305, если что.

**Comment by bukhmastov** [comment]
Не та репа, тут ведется только разработка приложения под андроид. Телеграм бот в другой репе и от другого разработчика.
